export const Images = {
  onBoarding: require('./Images.jpg'),
  LoginGradientBG: require('./LoginGradientBG.webp'),
  LoginVegetable: require('./LoginVegetable.webp'),
  googleLogo: require('./pngwing.png'),
  getStarted: require('./getStarted.jpg'),
  user: require('./user.png'),
  avatar: require('./avatar.png'),
  banner: require('./banner.png'),
  groceryStoreImages: {
    0: require('./Group9.png'),
    1: require('./Rectangle18.jpg'),
  },
  groceryCategoryImages: {
    0: require('./Category1.webp'),
    1: require('./Category2.webp'),
    2: require('./Category3.webp'),
  },
  orderEditSuccess: require('./OrderEditSuccess.webp'),
  amex: require('./Amex.webp'),
  discover: require('./Discover.webp'),
  visa: require('./Visa.webp'),
  mastercard: require('./Mastercard.webp'),
  freePlanModal: require('./freePlanModal.webp'),
  noPreference: require('./NoPreference.webp'),
  shopSuccess: require('./ShopSuccess.webp'),
};
