import { Receipt } from '../store/receiptStore';

export interface TranscationItemType {
  orderId: string;
  newDate: string;
  storeName: string;
  subTotal: string;
  orderStatus: string;
  inWishlist: boolean;
  reciept: Receipt[];
  uploadChannel: string;
}

export enum Intervals {
  'DAILY' = 'DAILY',
  'WEEKLY' = 'WEEKLY',
  'FORTNIGHTLY' = 'FORTNIGHTLY',
  'MONTHLY' = 'MONTHLY',
  'QUARTERLY' = 'QUARTERLY',
  'SEMI-ANNUALLY' = 'SEMI-ANNUALLY',
  'ANNUALLY' = 'ANNUALLY',
}

export enum UploadChannel {
  BARCODE = 'BARCODE',
  CSV = 'CSV',
  PHOTOS = 'PHOTOS',
  FORM_FILLING = 'FORM_FILLING',
}

export const UploadChannelDescription = {
  BARCODE: 'Uploaded Using Barcode Scanner',
  CSV: 'Uploaded Using CSV file',
  PHOTOS: 'Uploaded Using Camera',
  FORM_FILLING: 'Uploaded manually',
};

export const mockLocations = [
  { id: 'loc-1', name: 'Downtown Los Angeles' },
  { id: 'loc-2', name: 'Midtown Manhattan' },
  { id: 'loc-3', name: 'Bandra West, Mumbai' },
  { id: 'loc-4', name: 'Shinjuku, Tokyo' },
  { id: 'loc-5', name: 'Kreuzberg, Berlin' },
  { id: 'loc-6', name: 'CBD, Nairobi' },
  { id: 'loc-7', name: 'Richmond, Melbourne' },
  { id: 'loc-8', name: 'Jumeirah, Dubai' },
];

interface GroceryStore {
  id: string;
  name: string;
  address: string;
  rating: number;
  distanceKm: number;
}

export const mockGroceryStores: Record<string, GroceryStore[]> = {
  'loc-1': [
    {
      id: 'store-1',
      name: 'FreshMart LA',
      address: '123 Spring St, Los Angeles, CA',
      rating: 4.5,
      distanceKm: 1.2,
    },
    {
      id: 'store-2',
      name: 'Organic Zone',
      address: '456 Main St, Los Angeles, CA',
      rating: 4.2,
      distanceKm: 2.0,
    },
  ],
  'loc-2': [
    {
      id: 'store-3',
      name: 'Gotham Grocers',
      address: '789 5th Ave, New York, NY',
      rating: 4.7,
      distanceKm: 0.9,
    },
    {
      id: 'store-4',
      name: 'Whole Daily',
      address: '1011 Broadway, New York, NY',
      rating: 4.3,
      distanceKm: 1.5,
    },
  ],
  'loc-3': [
    {
      id: 'store-5',
      name: 'Apna Bazaar',
      address: '22 Hill Rd, Bandra West, Mumbai',
      rating: 4.4,
      distanceKm: 0.7,
    },
    {
      id: 'store-6',
      name: 'Nature’s Basket',
      address: '45 Linking Rd, Mumbai',
      rating: 4.1,
      distanceKm: 1.8,
    },
  ],
};

export const mockTranscationHistory: TranscationItemType[] = [
  {
    orderId: '#AB372',
    newDate: '2025-07-27T00:00:00.000Z',
    storeName: 'Coles - Bondi',
    subTotal: '77.50',
    orderStatus: 'Estimated',
    inWishlist: false,
    uploadChannel: UploadChannel.PHOTOS,
    reciept: [
      {
        storeBranch: 'Coles - Bondi',
        category: 'Food',
        productName: 'Bananas',
        unitPrice: 15.5,
        quantity: 3,
        subTotal: 46.5,
        unit: 'kg',
        receiptId: '1',
      },
      {
        storeBranch: 'Coles - Bondi',
        category: 'Beverages',
        productName: 'Milk',
        unitPrice: 4.95,
        quantity: 2,
        subTotal: 9.9,
        unit: 'litre',
        receiptId: '2',
      },
      {
        storeBranch: 'Coles - Bondi',
        category: 'Food',
        productName: 'Bread',
        unitPrice: 3.2,
        quantity: 2,
        subTotal: 6.4,
        unit: 'loaf',
        receiptId: '3',
      },
    ],
  },
  {
    orderId: '#AB375',
    newDate: '2025-07-26T00:00:00.000Z',
    storeName: 'Woolworths - Sydney',
    subTotal: '149.00',
    orderStatus: 'Confirmed',
    inWishlist: true,
    uploadChannel: UploadChannel.CSV,
    reciept: [
      {
        storeBranch: 'Woolworths - Sydney',
        category: 'Food',
        productName: 'Chicken Breast',
        unitPrice: 22.0,
        quantity: 4,
        subTotal: 88.0,
        unit: 'kg',
        receiptId: '4',
      },
      {
        storeBranch: 'Woolworths - Sydney',
        category: 'Household',
        productName: 'Toilet Paper',
        unitPrice: 12.75,
        quantity: 2,
        subTotal: 25.5,
        unit: 'pack',
        receiptId: '5',
      },
      {
        storeBranch: 'Woolworths - Sydney',
        category: 'Food',
        productName: 'Tomatoes',
        unitPrice: 6.5,
        quantity: 3,
        subTotal: 19.5,
        unit: 'kg',
        receiptId: '6',
      },
      {
        storeBranch: 'Woolworths - Sydney',
        category: 'Beverages',
        productName: 'Orange Juice',
        unitPrice: 5.5,
        quantity: 2,
        subTotal: 11.0,
        unit: 'litre',
        receiptId: '7',
      },
    ],
  },
  {
    orderId: '#AB376',
    newDate: '2025-07-25T00:00:00.000Z',
    storeName: 'ALDI - Melbourne',
    subTotal: '235.60',
    orderStatus: 'Estimated',
    inWishlist: false,
    uploadChannel: UploadChannel.BARCODE,
    reciept: [
      {
        storeBranch: 'ALDI - Melbourne',
        category: 'Food',
        productName: 'Pasta',
        unitPrice: 2.8,
        quantity: 4,
        subTotal: 11.2,
        unit: 'pack',
        receiptId: '8',
      },
      {
        storeBranch: 'ALDI - Melbourne',
        category: 'Food',
        productName: 'Apples',
        unitPrice: 12.0,
        quantity: 2,
        subTotal: 24.0,
        unit: 'kg',
        receiptId: '9',
      },
      {
        storeBranch: 'ALDI - Melbourne',
        category: 'Household',
        productName: 'Dishwashing Liquid',
        unitPrice: 5.75,
        quantity: 1,
        subTotal: 5.75,
        unit: 'bottle',
        receiptId: '10',
      },
      {
        storeBranch: 'ALDI - Melbourne',
        category: 'Food',
        productName: 'Rice',
        unitPrice: 10.5,
        quantity: 2,
        subTotal: 21.0,
        unit: 'kg',
        receiptId: '11',
      },
      {
        storeBranch: 'ALDI - Melbourne',
        category: 'Beverages',
        productName: 'Coffee',
        unitPrice: 15.0,
        quantity: 1,
        subTotal: 15.0,
        unit: 'pack',
        receiptId: '12',
      },
    ],
  },
  {
    orderId: '#AB377',
    newDate: '2025-07-24T00:00:00.000Z',
    storeName: 'IGA - Brisbane',
    subTotal: '127.40',
    orderStatus: 'Confirmed',
    inWishlist: true,
    uploadChannel: UploadChannel.FORM_FILLING,
    reciept: [
      {
        storeBranch: 'IGA - Brisbane',
        category: 'Food',
        productName: 'Canned Tuna',
        unitPrice: 3.5,
        quantity: 4,
        subTotal: 14.0,
        unit: 'can',
        receiptId: '13',
      },
      {
        storeBranch: 'IGA - Brisbane',
        category: 'Food',
        productName: 'Potatoes',
        unitPrice: 8.0,
        quantity: 3,
        subTotal: 24.0,
        unit: 'kg',
        receiptId: '14',
      },
      {
        storeBranch: 'IGA - Brisbane',
        category: 'Dairy',
        productName: 'Yogurt',
        unitPrice: 4.5,
        quantity: 2,
        subTotal: 9.0,
        unit: 'pack',
        receiptId: '15',
      },
      {
        storeBranch: 'IGA - Brisbane',
        category: 'Food',
        productName: 'Minced Beef',
        unitPrice: 18.0,
        quantity: 2,
        subTotal: 36.0,
        unit: 'kg',
        receiptId: '16',
      },
      {
        storeBranch: 'IGA - Brisbane',
        category: 'Household',
        productName: 'Laundry Detergent',
        unitPrice: 13.5,
        quantity: 1,
        subTotal: 13.5,
        unit: 'bottle',
        receiptId: '17',
      },
      {
        storeBranch: 'IGA - Brisbane',
        category: 'Food',
        productName: 'Frozen Pizza',
        unitPrice: 9.75,
        quantity: 2,
        subTotal: 19.5,
        unit: 'pack',
        receiptId: '18',
      },
    ],
  },
  {
    orderId: '#AB378',
    newDate: '2025-07-23T00:00:00.000Z',
    storeName: 'Coles - Perth',
    subTotal: '189.90',
    orderStatus: 'Estimated',
    inWishlist: false,
    uploadChannel: UploadChannel.CSV,
    reciept: [
      {
        storeBranch: 'Coles - Perth',
        category: 'Food',
        productName: 'Eggs',
        unitPrice: 7.2,
        quantity: 2,
        subTotal: 14.4,
        receiptId: '19',
        unit: 'dozen',
      },
      {
        storeBranch: 'Coles - Perth',
        category: 'Dairy',
        productName: 'Cheddar Cheese',
        unitPrice: 8.5,
        quantity: 1,
        subTotal: 8.5,
        unit: 'pack',
        receiptId: '20',
      },
      {
        storeBranch: 'Coles - Perth',
        category: 'Food',
        productName: 'Pasta',
        unitPrice: 2.8,
        quantity: 4,
        subTotal: 11.2,
        unit: 'pack',
        receiptId: '21',
      },
      {
        storeBranch: 'Coles - Perth',
        category: 'Beverages',
        productName: 'Orange Juice',
        unitPrice: 5.5,
        quantity: 2,
        subTotal: 11.0,
        unit: 'litre',
        receiptId: '22',
      },
    ],
  },
  {
    orderId: '#AB379',
    newDate: '2025-07-22T00:00:00.000Z',
    storeName: 'Woolworths - Adelaide',
    subTotal: '294.75',
    orderStatus: 'Estimated',
    inWishlist: true,
    uploadChannel: UploadChannel.BARCODE,
    reciept: [
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Food',
        productName: 'Chicken Thighs',
        unitPrice: 20.0,
        quantity: 3,
        subTotal: 60.0,
        unit: 'kg',
        receiptId: '23',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Food',
        productName: 'Carrots',
        unitPrice: 5.0,
        quantity: 2,
        subTotal: 10.0,
        unit: 'kg',
        receiptId: '24',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Beverages',
        productName: 'Tea Bags',
        unitPrice: 6.5,
        quantity: 1,
        subTotal: 6.5,
        unit: 'pack',
        receiptId: '25',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Food',
        productName: 'Cereal',
        unitPrice: 7.0,
        quantity: 2,
        subTotal: 14.0,
        unit: 'box',
        receiptId: '26',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Household',
        productName: 'Paper Towels',
        unitPrice: 4.75,
        quantity: 3,
        subTotal: 14.25,
        unit: 'pack',
        receiptId: '27',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Food',
        productName: 'Salmon Fillet',
        unitPrice: 30.0,
        quantity: 2,
        subTotal: 60.0,
        unit: 'kg',
        receiptId: '28',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Dairy',
        productName: 'Butter',
        unitPrice: 5.5,
        quantity: 2,
        subTotal: 11.0,
        unit: 'pack',
        receiptId: '29',
      },
      {
        storeBranch: 'Woolworths - Adelaide',
        category: 'Food',
        productName: 'Avocados',
        unitPrice: 3.0,
        quantity: 4,
        subTotal: 12.0,
        unit: 'pcs',
        receiptId: '30',
      },
    ],
  },
];
